name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: LaTeX compilation
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: main.tex
      - name: Archive Logs
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: logs
          path: main.log
      - name: Archive PDF
        uses: actions/upload-artifact@v1
        with:
          name: pdf
          path: main.pdf
